### ISSUE TITLE
Questions sur les spécifications fonctionnelles

### ISSUE THREAD

**Issue by Selma1** [tedramoni/Mastermind#1]
Comment calcule-t-on le score ? 

Comment le joueur choisit la case dans laquelle il veut positionner son symbole ?

**Comment by astamarr** [comment]
- avec le nombre de try en échec
- Question d'UI. En console t'as tout les inputs clavier.

2015-12-08 16:34 GMT+01:00 Selma Caglayan <notifications@github.com>:

**Comment by killwithabass** [comment]
EDIT
Aucune notion de score n'a été indiqué dans le besoin.
Nous laissons à votre appréciation la méthode de sélection de la case.
