### ISSUE TITLE
Remarques

### ISSUE THREAD

**Issue by ViBiOh** [tedramoni/Mastermind#2]
# Remarques
## MOA
- Scénarios de tests corrects
## MOE
- Spécifications encore un peu légères et toujours pas de code ?
## Git
- Bonne utilisation des commentaires

**Comment by ViBiOh** [comment]
# Remarques

Expression_de_Besoin.md

"Au démarrage de l'application en console" -> Forcément une application console ?
"Nombre de joueur" -> avec un petit "s"
"L'IA demandé" -> demandé*e*

Scénarios_de_tests.md

"en conservant les paramètres de départ (taille de grille" -> La taille de la grille n'est pas un paramètre
Incohérence entre "L'application relance une partie en augmentant le niveau de difficulté de l'AI" et "Si le joueur joue contre l'IA, on lui propose de rejouer en changeant le niveau de difficulté."

Spécifications fonctionnelles.md

"pas d'ordre de placement des jetons blancs et noirs" -> comment ils indiquent une couleur bien placée ?
Revoir la réponse du cachotier, en l'état c'est impossible.

**Comment by Seefy** [comment]
Pour chacune des remarques, les corrections ont été apportées.
