### ISSUE TITLE
Question technique sur le placement des symboles

### ISSUE THREAD

**Issue by ThomasPerche** [tedramoni/Mastermind#3]
Bonjour,

Je souhaitais savoir comment est ce que vous vouliez qu'un joueur puisse placer ses symboles sur la grille.

Option 1 : Il doit entrer les coordonnées de la grille, type (x,y) abscisse et ordonnées
Option 2 : Il doit entrer le numéro de la case de la grille, exmple : de 1 à 9 pour une grille type 3x3

**Comment by killwithabass** [comment]
" Rien n'est précisé là dessus dans le cahier des charges donc vous etes  libres de choisir l'option qui vous semble la mieux. Tant qu'elle est justifié elle nous satisfera. "

 *Copie de ma réponse faite sur FB le 31 dec 2015*
